CREATE TABLE IF NOT EXISTS deviceAudits (
    id SERIAL PRIMARY KEY,
    deviceId BIGINT UNSIGNED NOT NULL,
    type VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    details TEXT,
    FOREIGN KEY (deviceId) REFERENCES devices(id) ON DELETE CASCADE
);