ALTER TABLE devices ADD COLUMN updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE deviceAttributes ADD COLUMN updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE deviceCapabilities ADD COLUMN updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
